### ISSUE TITLE
Feature Request: manage SSL from Web GUI

### ISSUE THREAD

**Issue by dinger1986** [wh1te909/tacticalrmm#126]
I have setup a CRON job but it would be good to manage SSL Certs from the portal as well.

**Comment by wh1te909** [comment]
can you post the cron command you used? Im not sure if the TXT challenge option the install script uses can be automated since would have to manually add the TXT record but I know there are other ways like wellknown challenge.

**Comment by trs998** [comment]
I used the following manually, using the DNS TXT record method. The usual standalone method for certbot won't work due to the RMM being a seperate server to the webserver on the primary domain... could make seperate certs for each of the three subdomains and then use standalone on those rather than the existing wildcard certificate which must be verified on a domain not directly hosted by this server? 

DOMAIN="mydomain.tld"
certbot certonly --preferred-challenges dns --manual -d *.$DOMAIN --agree-tos --manual-public-ip-logging-ok

Note - this makes a new certificate which must be manually moved into /etc/letsencrypt/live/$DOMAIN/ or the places that refer to the SSL certificate updated. Look in /etc/letsencrypt/live/$DOMAIN-XXXX where XXXX is the highest number for the latest certificate.

Note - there appears to be no documentation or automation of the SSL renewal - possibly add a manual run of this in the update.sh script if required and being run interactively?

**Comment by dinger1986** [comment]
this should be covered in the docs when they come, there is a script for doing this automatically via dns or can manually do it with DNS. Going to close this now
