### ISSUE TITLE
Feature Request: System Counters for Online and etc.

### ISSUE THREAD

**Issue by netwalker0099** [wh1te909/tacticalrmm#132]
![SystemCounts](https://user-images.githubusercontent.com/23370989/95474264-8a73b200-094a-11eb-87fd-61dd6b484c0b.PNG)

Could we add system counts for number of total installed agents, total agents online where i've made the red circle, and counts for each site as you select it for the blue circle, like Desktops Install, Servers Install, Desktops Online, Servers Online.

**Comment by wh1te909** [comment]
The red circle part yea but the blue circle can't do it there, on my rmm i have alot of clients so that part is actually taken up by clients lol and would be for anyone else that has more clients. I was planning on adding a separate dashboard with a ton of metrics but for now i can add some basic info along the top in your red circle

**Comment by sadnub** [comment]
@netwalker0099 I started on this and #141 should add some agent total indicators to the red portion of the dashboard you highlighted. Clicking on the online/offline will then breakout the workstation and server totals.
