### ISSUE TITLE
Feature Request: Re-Usable Download Links for Agents

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#138]
Would it be possible to add somewhere to re-download generated agents rather than regenerating them every time?
The list would be similar to the image below (excuse the quick mock-up in excel)

Expired links would disappear from the list and agent files stay on the RMM server until the expiry date and are automatically deleted. We could then just copy and paste a link to a client machine to download and install the agent rather the transferring the installer.

Also might be good to show the agent version generated in the table too.

![image](https://user-images.githubusercontent.com/15325110/95718458-d52a5c80-0cb1-11eb-9d31-24b77fc6af64.png)

**Comment by saulens22** [comment]
I don't think exe file archive is good idea. API endpoint would be more universal. Something like `/api/generate/agent/x64/exe/{agent-hash}` or `/api/generate/agent/{client}/{site}/x64/exe/{user-api-key}`. Would be good for getting raw PowerShell script too.

**Comment by wh1te909** [comment]
yea would not want to keep the actual binaries sitting on the server since it would not only take up space but if I update the installer with a new function or something the old binary might not be compatible anymore.

It only takes 2 seconds to generate an exe on the fly, so I'm thinking something like how meshcentral does it, generating an "invite" link which has an expiration and can have a section that shows all that info like your excel mockup, and then when you copy and paste that link into a browser at your client's site or whatever it will just generate the exe and download it then and there.

what do you guys think?

**Comment by bradhawkins85** [comment]
Sounds great to me.

**Comment by wh1te909** [comment]
Done, please update and try it out and lmk. Agents > Manage Deployments.

**Comment by dinger1986** [comment]
Working fine for me, we have sent afew customers the link and they have installed the agent, working great!

**Comment by saulens22** [comment]
Confirmed working.

**Comment by bradhawkins85** [comment]
So far so good, haven't needed to generate many downloads but the ones I have worked perfectly.
