### ISSUE TITLE
Enhancement request: Reduce mouse clicks to create agent deployment file

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#164]
While right-clicking the specific client's site, it would be great if there was a way to have a direct link to create an installable agent for that specific site of that specific client, or at least open the "install agent" window with those details pre-loaded for the lazy admin.

![image](https://user-images.githubusercontent.com/32017425/97818320-78b3cf00-1caa-11eb-9e39-ce2af0a20222.png)

![image](https://user-images.githubusercontent.com/32017425/97818375-bb75a700-1caa-11eb-8235-3dc0323fcd2a.png)

**Comment by wh1te909** [comment]
You can already do this via client/site deployments. Agents > Manage Deployments. If you don't see it then make sure to run the update.sh script so you're on the latest version.

![deployment](https://user-images.githubusercontent.com/7434746/97831189-2790e480-1c84-11eb-84b7-d636781deeea.PNG)

**Comment by DjMagicFingers** [comment]
Sure, that is a very important feature to be able to generate a permanent link and send it to the client, but that was not my intention.
I was referring the request for ease of usage by reducing the amount of clicks needed to initiate the "install agent" window and have the details pre-entered in a manner that reflects the item that I have clicked on.

The Deploy screen, as important as it is, forces the user to deal with creation of links per client.

**Comment by wh1te909** [comment]
got it, was just thinking it's alot faster to generate a permanent link (set expiry to like 2040 lol) once for each client or site and then you can just reuse that link for yourself everytime you want to install an agent, personally have been doing it that way and haven't needed to use the "Install Agent" screen since.

I will add your "create agent deploy" button to the client/site tree and have it open the "install agent" window with the client/site already pre-selected

**Comment by wh1te909** [comment]
@DjMagicFingers This has been implemented by @sadnub, will be in the next release later tonight or tomorrow

![deploy](https://user-images.githubusercontent.com/7434746/100532939-9db93600-31b3-11eb-87b3-e8477ded6880.png)
