### ISSUE TITLE
Enhancement request:  Dynamically create Clients and Sites from agent deployment

### ISSUE THREAD

**Issue by JRM-SC** [wh1te909/tacticalrmm#183]
We have several dozen clients, some with multiple sites each.  Pre-configuring each client and site then a specific agent deployment is a bit tedious with the smaller 5 to 10 user locations.

It would be very useful to have a generic agent deployment for which you can specify the client name and site name strings as arguments and allow the RMM to create the Client/Site if they don't already exist and add the new agent.

Something like:
/Client-Name "Example Client" /Site-Name "New Site"

**Comment by wh1te909** [comment]
The dynamically generated exe is just a wrapper around the generic binary that simply bakes the command line arguments into the generic exe so you don't have to pass them.

If you choose the "Manual" method from the Install Agent menu, you will see the command line needed to pass to the winagent-vx.x.x.exe which is the generic binary, as well as the download link for the generic exe. You'll need to use the client and site ID's instead of the names for now, until I add the ability to pass the client/site name and create if doesn't exist. So for now you can just use the manual method to figure out the client/site id's for each client and then set the token expiration for a year or whatever and you pretty much have a generic deployment minus the dynamic client/site creation.

**Comment by JRM-SC** [comment]
Thanks @wh1te909, I've actually used the manual deployment method for our larger clients dropping the winagent on their local file server.  Would be great to see the automatic site creation since I can script out a mass installation using Client/Site names in our current remote access system.

**Comment by dinger1986** [comment]
@JRM-SC is this still a feature you require? we do it by having one generic client on tactical and all goes into there then move it into the correct client.

**Comment by JRM-SC** [comment]
@dinger1986 I would do it this way if I could mutli-select agents and bulk edit/move them to a new Client or Site.

**Comment by dinger1986** [comment]
fair enough, I have managed to do it fine with over 500 agents deployed.

**Comment by JRM-SC** [comment]
Definitely not saying it can't be done but it's not the fastest process editing each individual agent and changing the location.  We're sitting at 475 systems with TRMM installed out of 1140 in our Connectwise instance.

Below are some screenshots of how Connectwise Control handles multi-select and bulk actions as an example. 


![CW Control Multi-select](https://user-images.githubusercontent.com/488745/113728117-c56d5d00-96c3-11eb-8c77-c192e7b83efe.png)

![CW Control Edit](https://user-images.githubusercontent.com/488745/113728115-c56d5d00-96c3-11eb-9a98-cc825f3a9376.png)

**Comment by sadnub** [comment]
This is now possible using the tactical api in a PS script. You can wrap the installer with it and create the client/site and pass those variables to the installer for the agent.
