### ISSUE TITLE
Feature Request: Warning State for Monitors

### ISSUE THREAD

**Issue by mfeuhrer** [wh1te909/tacticalrmm#184]
It would be nice to have a Warning state for monitors, besides just pass/fail. A yellow condition can be useful for information that could be a problem, but isn't yet. 

Would be very useful for memory/CPU checks as well as script results.

**Comment by wh1te909** [comment]
I could make the status Warning instead of Failing if the "number of consecutive failures before alert" is set to any number higher than 1 but less than the actual consecutive failure count, and have it change to Failing once that number is reached. Does that work?

Otherwise don't really see how to differentiate between warning or failing. Maybe for script checks if you return a custom return code in your script like 99 or something unique we can reserve that for a "Warning" status. Right now scripts pass if they return 0 and any other number will be a fail.

**Comment by bradhawkins85** [comment]
what about two options, one for Warning Count and one for Failure Count?
I'm currently seeing MeshAgent.exe using >3GB of RAM at times so killing the agent brings everything back to normal. With a warning we could trigger a script to fix the problem (but not fire an email for example) then if that doesn't help send the email alert on failure for further investigation.

**Comment by mfeuhrer** [comment]
Let's take the CPU item for example. My thought would be to have anything below 70% consumption be passing, 70-90% consumption warning, and 90-100% consumption be a failure. At least on resource monitors, being able to tie this to a numeric range or percentage would be great. 

You're dead on with the script check idea. We can exit with just about any error code number. 0 for pass, 1 for fail, 2 for warning (or 99, or whatever works easiest).

**Comment by wh1te909** [comment]
released in 0.4.8

**Comment by mfeuhrer** [comment]
Amazing thanks!
