### ISSUE TITLE
New User + 2FA

### ISSUE THREAD

**Issue by juaromu** [wh1te909/tacticalrmm#195]
Hi:

I created a new user, while logged on as admin, logged off and back on with the new credentials.
When presented with the Q code to enable 2FA I could actually access the portal without completing the process, just by retyping the main RMM URL in the browser. The account on the top right was shown as "undefined", but with full access to the portal.
Not sure if this is an expected outcome, must confess I found out "by mistake" while logging on to test the new account for the first time.
After that, you won't be able to log on again with the "unfinished account" since the portal asks for the 2FA code and that was never initialized.

**Comment by wh1te909** [comment]
Hi yes that's normal. When a new user is created, the first time they login, since they haven't setup 2 factor yet, a temporary token is created for them which is stored in the browser's cache, that way they can access the 2 factor page to scan the barcode with their phone. And then once scanned and when click "Finish" it will take them back to login screen. But yea if you don't scan the barcode and click the finish button and just go straight to the portal then the user will show as "undefined".

You can just reset their 2 factor token by right clicking on the user and reset 2 factor, then next time they login they will be taken to the 2 factor page again to scan barcode.

![reset2fa](https://user-images.githubusercontent.com/7434746/100571319-bb57cf80-3287-11eb-9015-256313490d33.png)

**Comment by juaromu** [comment]
Cool, that makes sense :-)
Thanks heaps for your answer and explanation.
Regards.
