### ISSUE TITLE
Internal server certs

### ISSUE THREAD

**Issue by Uzzi** [wh1te909/tacticalrmm#196]
HI, I wanto to deploy RMM into internal server, no external exposure, than install.sh notify me: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "*.DOMAIN.intranet": Domain name does not end with a valid public suffix (TLD)

How can I fix it?
Thank you

**Comment by Uzzi** [comment]
I've created certs by: sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/selfsigned.key -out /etc/ssl/selfsigned.crt

I've edited install.sh and modifyed certs sections.

But now I cannot login. Error: Bad credentials

**Comment by wh1te909** [comment]
Hi, self signed certs will no longer work since we switched to NATS which is why I removed them from the install script.

You can still get a free let's encrypt cert for internal use, you don't need to open any ports. If you don't have a domain just get a free one from freenom.com

**Comment by meyerje** [comment]
Does this remove support for an internal root CA as well?

**Comment by wh1te909** [comment]
@meyerje no that should still be fine cuz yours is a proper cert, NATS just doesn't like ghetto ones generated by openssl. Will DM you on discord cuz I need to you test.

**Comment by Uzzi** [comment]
Can I configure Tactical to work only with interna domain and ask let's encrypt cert for other public domain?

**Comment by wh1te909** [comment]
@Uzzi yea so NATS needs a valid certificate, which doesn't necessarily have to be the same cert used for the rmm website so I guess you could use the self signed cert for everything except NATS, and then use a letsencrypt cert just for NATS.

 I'll be releasing an update soon with that option, so I will follow up with you then with instructions.

**Comment by Uzzi** [comment]
@wh1te909 Hi, I've new installation with  letsencrypt certs, but same Error: Bad credentials
How can I reset admin password from cli?

**Comment by Uzzi** [comment]
@wh1te909 during agents installation, I've certification x509 error.

**Comment by wh1te909** [comment]
@Uzzi im not familiar at all with certs but i think prolly you have to add the cert in the agent's trusted cert store or something. Which is why I recommend you just do letsencrypt or get a proper cert and you wont have any of these errors.

I did some optional settings in the latest release in 0.2.4 for using custom certs though if you want to try

you can add the 2 following variables to the bottom of `/rmm/api/tacticalrmm/tacticalrmm/local_settings.py`

```
CERT_FILE = "/path/to/your/fullchain.pem"
KEY_FILE = "/path/to/your/privkey.pem"
```

then do a `sudo systemctl restart rmm` and from the web interface, go to Tools > Server Maintenance > Reload Nats
then check `sudo systemctl status nats` and see if there are any certificate errors or just try installing an agent again
Note that these custom certs are only for NATS, not for nginx. You can read more about the NATS cert requirements here: https://docs.nats.io/nats-server/configuration/securing_nats/tls#certificate-authorities

For nginx you should still be able to use a ghetto cert generated by openssl

**Comment by Uzzi** [comment]
I've changed all certs (no NATS), nor at admin page: Server Error (500)
Where can I find logs?

**Comment by Uzzi** [comment]
After https://apirmm.cdlmvenezia.intranet/xxxxxxxxxxxxxxxxxxxxxxxxxx login--->Server Error (500)
