### ISSUE TITLE
Patches Installed Date - Not showing

### ISSUE THREAD

**Issue by KenGrant** [wh1te909/tacticalrmm#199]
In the last few releases the installed date of any patches is no longer showing - perhaps because all mythe PC's / Server are using UK date format - dd/mm/yyyy ?

Thanks

**Comment by wh1te909** [comment]
the installed date will only show if the update was installed by the tactical agent, any previous updates won't show an installed date. Timezone / format doesnt matter since its generated by the rmm not the agent. I wouldn't worry about it since i am rewriting the winupdate module in the agent from scratch so its all going to change soon and start fresh.
