### ISSUE TITLE
Take Control - Get a PopUp to user to acknowledge the access of an engineer

### ISSUE THREAD

**Issue by rail3r** [wh1te909/tacticalrmm#229]
Hello,

Is it possible (maybe it is already) to get some access control on the TakeControl option ? so the users allow the connection.
Or Deny :)

Only when it is a Workstation (Windows, Mac, Linux) - When the policy is a Server then it should not have these access control.

Thanks in advance.

**Comment by dinger1986** [comment]
This is built into mesh already.

so what to do is this
1. Log into tactical
2. Right click and take control on any PC
3. In another tab Go to https://mesh.yourdomain.com
4. Click on TacticalRMM Group (or go to my account then Tactical RMM)
5. Click on Edit button next to User Consent and set the settings that you would like configured
6. In User Authorisations and select the default account created by Tactical (if you have multiple it should show as Full Administrator)
7. Next to Real Name  click the edit button and change this to the name you want customers to see, for example for us we have it set as the business name rather than individuals.

There are loads of people to help on the discord channel as well.

**Comment by wh1te909** [comment]
thanks @dinger1986

**Comment by daksh-1201** [comment]
I do not see the edit pencil beside the User Consent... Do I need to make changes in the config.json????
![Screenshot 2024-07-10 at 8 08 37 AM](https://github.com/amidaware/tacticalrmm/assets/175176537/ac86f4b5-664b-4646-a9d0-42474d1b9a98)

**Comment by silversword411** [comment]
> I do not see the edit pencil beside the User Consent

Probably because you're using the new meshcentral permissions sync feature in TRMM. You need to manually login to mesh with your original superadmin user to adjust that manually

**Comment by Vihvila92** [comment]
Is there any plan to integrate this option to main Tactical GUI? I am not fun of the two portal setup.

**Comment by dinger1986** [comment]
the default is that it shows that a user is accessing the machine, if you want to change this please follow the above as its a one off change.

**Comment by alencarwell** [comment]
Hello, i dont working this funtion in documentation.
please, helpme?
https://docs.tacticalrmm.com/tipsntricks/#enable-remote-control-options

If you need to comply with GDPR regulations and ensure employee rights legislation is complied with, you can make sure that users receive a popup to inform them so they are aware when your techs log in and connect to their machine. You can enable a banner that shows when a remote connection is established.

Login to meshcentral as the [mesh superuser](https://docs.tacticalrmm.com/mesh_integration/#get-a-url-to-login-to-mesh-as-the-mesh-superuser).
Click on My Account
Click on the device group you want to enable notifications or accept connection etc on (probably TacticalRMM).
Next to User Consent click edit (the wee pencil)
