### ISSUE TITLE
Feature Request: Policy Tasks - Schedule Task for directly after agent install.

### ISSUE THREAD

**Issue by technoicon** [wh1te909/tacticalrmm#247]
In policy tasks.

It would be nice if you could scheulde a task to be run directly after an agent has been installed.
Maybe this could be a run once option, 5 mins after agent install.

For example:
I'd like to run the script "Rename Tactical RMM Agent" directly after install, without having to run it manually.

This would allow a lot of onboarding scripts to also be run once on agent install.

**Comment by bradhawkins85** [comment]
Try scheduling a one time script for the current date / time, I've got a couple set up that way and they run not long after the first check in.

**Comment by technoicon** [comment]
So the tasks run even if scheduled in the past?

I was also thinking an option to "run now if never run before", would also work.

**Comment by bradhawkins85** [comment]
To be honest I haven't verified with the later builds of the RMM but it has been working for me in the past.

**Comment by wh1te909** [comment]
I just added a new option to the task UI which will check the "Run task as soon as possible after a scheduled start is missed" checkbox in Windows Task Scheduler, thinking that would allow this feature. Turns out if the scheduled date of the task is in the past, this checkbox has no effect; Windows won't run the task even with that box checked.

But anyway, turns out this feature has been implemented for a while now, since when you create a task in tactical, I'm actually checking to see if the scheduled date you chose is in the past and if so, to change it to the current time + 5 minutes.

So yes as @bradhawkins85  said the way to make this feature work is to create a policy task, choose "Run Once" for the schedule, and set the run date to 1999 or something in the past. 

Then apply the policy to a client/site, and when you install a new agent that's in the client/site of the policy, immediately after the agent installs, you'll see the task show up in the web UI under the "Tasks" tab. And you'll see the scheduled run time date will be the time of the agent install + 5 minutes, so essentially right after agent install.
