### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by sadnub** [wh1te909/tacticalrmm#3]
Hello,
I just wanted to say that this project and the work done is awesome! I am currently splitting up the different components in docker so that I can test this myself. Would you be interested in adding the docker configuration to the repo? I can do a pull request once I get everything working.

Thanks!

Josh

**Comment by wh1te909** [comment]
Hi, appreciate the kind words. Yes docker support would be amazing! I see your pull request and will review when I can and merge it, have been super busy past few days but will get to it as soon as I can.

**Comment by sadnub** [comment]
@wh1te909 Thanks! I have been testing this a little more and I found that the meshagent upload isn't working on the initial client/site creation. Also adding a site to an existing client gives an issue. This might be an issue with the docker server configuration, but not sure. I get a CORS error, but the app domain is already whitelisted in Django.

I am also confused on how the MeshCentral server interacts with the tactical rmm service. Do I need to manually create a mesh group? Is the Mesh Server just used as a means for remote control of the managed endpoint? I also can't verify that the salt service is working as expected.

**Comment by wh1te909** [comment]
Merged your pull request.
I just updated the readme with an example walk-through of a full installation start to finish. I was running into CORS errors myself during file uploads, but it was actually due to file/folder permissions, once fixing that the CORS errors went away. The install script sets the correct permissions.

Yes you need to create a mesh group manually, check the updated readme for instructions. meshcentral and tacticalrmm are not really connected, I just wrap the meshcentral site in an iframe and use meshcentral's logintoken command line feature to generate a token which gets passed in the url of the iframe for authentication. The 2 django views that handle this are meshcentral_tabs() and take_control() in agents/views.py

Let me know if you are able to get a full installation working on a normal VPS without docker and then if all works can start troubleshooting docker, I think most of the errors you are getting are due to permissions. I have very limited docker experience and the way tacticalrmm works with salt and meshcentral I just thought would be too complicated for docker which is why I never even tried lol. But I am going to play around with your docker setup and see what errors I run into and try to get it working.

**Comment by sadnub** [comment]
Thanks for the info! I checked the readme updates and that definitely clears up the questions I have. I am using a chromebook for my dev environment, so docker is the best I have. I will do some testing and I might need to submit another pull request once I have the issues ironed out. 

I can also use docker to spin up some agents to connect to the dashboard. That would verify the salt configuration works.

Also. do you have a road map of features you are planning to implement? I would love to assist in development and testing.

Thanks again!

Josh

**Comment by wh1te909** [comment]
Sweet! Yea I'll add a road map of features I plan on adding. Not sure if you've ever used solarwinds rmm, we currently use that at my work so this project is heavily inspired by that, the plan is to eventually replace solarwinds with this so whatever features they have I'm trying to implement.

**Comment by sadnub** [comment]
I haven't used Solarwinds in particular, but am familiar with RMMs. Mostly Labtech, Continuum, and Atera. I'll test out the UI more and see about adding some features. One of the things that jumped out at me were the OTP code being stored in the database under the user versus config. 

I was also having an issues adding an additional site under a customer.

Also an Alerts overview might be useful. I might have some time this weekend to test some of this out. 

I'm still getting used to Django being from a Laravel background. I'm starting to really like it!

**Comment by wiicode** [comment]
Just want to say I hit this as well.  I had a few false starts but so far everything looks good except `"core/uploadmesh/ 500 (Internal Server Error)"` when trying to send the Mesh agent file up to complete the setup.  Also Dockerized.

**Comment by Traace** [comment]
Same happens with a clean traditional install. The Server last for about 2 hours and its already broken because of a attempt to reinstall a single client.

(Yes I followed the guide exactly with a clean ubuntu 20.04)

To unstable for my needs. Looking for another solution now.
