### ISSUE TITLE
Feature Request: Make SSL optional in the installation script

### ISSUE THREAD

**Issue by techmed5** [wh1te909/tacticalrmm#370]
When installing the tactical RMM server behind a proxy that hosts multiple HTTPS sites on a single IP it causes communication issues from the clients. As the proxy provides the SSL, it is an issue with dual SSL being present since the RMM server preinstalls one. It seems to block traffic for meshcentral, scripts, and status updates on update patching. Client installs do complete and report online status. If presenting on option for the SSL to be installed will not affect any other functionality then please consider that as a prompt. Otherwise, disregard this request as it isn't worth any other workarounds and we'll do something with the proxy.

**Comment by wh1te909** [comment]
Hi, yea tactical is not your standard web app there are some background services other than nginx that need access to the SSL cert for everything to work, so removing it from install would cause issues. I know @bradhawkins85 runs it behind haproxy, see his comment here for his setup https://github.com/wh1te909/tacticalrmm/issues/135#issuecomment-706935736

If you don't want to use letsencrypt certs then you'll need to add the following 2 variables to `/rmm/api/tacticalrmm/tacticalrmm/local_settings.py` and then make sure the file perms are readable by the `tactical` linux user or whatever user you ran the install script with. Otherwise trmm will look for these 2 certs in `/etc/letsencrypt/live/<yourdomain.com>/`

```
CERT_FILE = "/path/to/fullchain.pem"
KEY_FILE = "/path/to/privkey.pem"
```
