### ISSUE TITLE
Question - Server spec required

### ISSUE THREAD

**Issue by VINISHVV** [wh1te909/tacticalrmm#378]
I am planning to deploy TRMM tool @ my office.
Expecting approximate 200+ users and 10K systems.
Can you share the required server spec, Bandwidth etc......

**Comment by dinger1986** [comment]
All information is available in the documentation.

https://wh1te909.github.io/tacticalrmm/install_server/

**Comment by wh1te909** [comment]
im curious to see the performance with 10k agents lol, highly doubt anyone is running anywhere near that many agents
let us know how it goes :)

**Comment by VINISHVV** [comment]
Dear Dan,

I am running Meshcentral with more than 10k agents. There is no issues till now.
I hope tacticalRMM also support that much agents.

**Comment by wh1te909** [comment]
@VINISHVV yes tactical can support 10k agents but I have no idea what the requirements will be, I guess just start installing and monitor the usage. RAM should not really be affected by the amount of agents, CPU cores/speed prolly will be the bottleneck

I currently run around 750 agents in production, my RAM usage hovers around 1.63GB and I have 4 cores (but they're AMD Ryzen's super fast) and load average is pretty small. Am also running NVME drives so that helps a ton as well

**Comment by VINISHVV** [comment]
Installed 780 agents today and works properly till now.... 

Rest of 2000  agents scheduled on tomorrow
