### ISSUE TITLE
Feature request: Option to show the output of running a "favourite script"

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#403]
At present, you cannot run a favourite script if you want to read the output. It's a "fire and forget". 

An option to be able to wait x seconds for the result of the script (like the "run script" option does).

If this is too tricky to put in place, an easier alternate maybe have "Favorite scripts only" filter in "run scripts" dialogue to make them easier to find/select.

**Comment by wh1te909** [comment]
So actually the original purpose of the run favorite script feature was to just have a super fast way to quickly run a script without dealing with multiple clicks like in the "Run Script" menu. 

And if you wanted output then it was only just a few more clicks to do the Run Script method and wait for output.

This was back when there were waaay less community scripts than there are now and so yes definitely needs to be improved, actually issue #374 should solve this since we'll add a search feature to the dropdown and I can also add your "favorite scripts only" filter too

**Comment by manc74** [comment]
Yes the favorites filter will work just as well, thanks.

**Comment by Serg86** [comment]
Perhaps a nice addition would be a history of previous manually executed scripts for each machine, where you can see the output etc., like you already can for checks and tasks.

**Comment by wh1te909** [comment]
released in 0.8.0
