### ISSUE TITLE
Bug: SATA Storage drives are showing IDE

### ISSUE THREAD

**Issue by johnnyq** [wh1te909/tacticalrmm#411]
**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Browser: [FireFox]
 - RMM Version (0.6.1):

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (1.5.1:
- Agent OS: [e.g. Win 10 v2004]

**Describe the bug**
Storage drives are showing IDE under hardware details when they are SATA

**To Reproduce**
1. Cick Agent
2. See Hardware Details

**Expected behavior**
Should see SATA not IDE

**Screenshots**
![Screenshot from 2021-04-17 16-25-39](https://user-images.githubusercontent.com/1812594/115126002-f9852f80-9f99-11eb-8c67-fac01e006918.png)

**Additional context**
This is affecting all agents that have SATA

**Comment by wh1te909** [comment]
Run `wmic diskdrive get InterfaceType`

Windblows seems to always return IDE no matter what, unless it's SCSCI so if you know of another way to get this lmk, i can look into it later

**Comment by azulskyknight** [comment]
Yeah this is an old Windowsism.

SATA, is ATA.  That is... IDE.  It's just serially connected, instead of connected in parallel via ribbon cables.

SCSI is different, and usually only for special stuff with special drivers.  SAS, and NVME devices often use SCSI drivers, but I've also seen NVME use ATA and therefore report IDE.

So while cosmetically I can see the confusion, but at the end of the day SATA IS IDE, so what's reported is technically correct.
