### ISSUE TITLE
Skip letsencrypt when sitting behind an existing reverse proxy

### ISSUE THREAD

**Issue by doughecka** [wh1te909/tacticalrmm#42]
I have an existing ngnix reverse proxy (with integrated letsencrypt) that serves my single public ip address that I have available to me. Is it possible to skip the letsencrypt process (perhaps using a self-signed cert or allow http)? Alternatively, can I configure it to use an alternative port (81/444, for example) so it can coexist with my existing public services?

**Comment by wh1te909** [comment]
Hi, you'll just need to go through the install script manually and not run the sections that are already setup, since the install script assumes a fresh vps. I have pretty much the same setup as you described for my dev environment (self signed certs, http). Give it a try and let me know if any issues so I replicate
