### ISSUE TITLE
Feature Request: change default description for hosts in the table of computers

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#424]
**Is your feature request related to a problem? Please describe.**
I personally would prefer the default description to be blank because when I do add descriptions, I have to read through hostnames which feels like a waste of brain cycles. Also the information is redundant. If it can't be blank then I would prefer `.` or `_`. 

Other ideas:
* make the default description a system preference
* someone on discord suggested the default `Enter a description` (I vote no on this idea)

Bonus:
* add `{{ .... }}` macro capabilities

**Comment by wh1te909** [comment]
Guess I used to have it documented somewhere but don't see it anymore, but if you pass the `-desc "some description"` flag to the installer exe it will actually set it to whatever you pass, if you don't pass this optional flag the default is just the hostname. I'll just change the default to be an empty string instead of the hostname.

**Comment by wh1te909** [comment]
Released in 0.6.2 / agent 1.5.2, from now on any new agents will have default hostname set to an empty string and you can set the description with the optional `-desc` flag during install
