### ISSUE TITLE
Bug: cannot log in to mesh.domainname.com

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#429]
After upgrading to 0.6.2 we can only log in to rmm.domainname.com but not mesh.domainname.com 
Before the upgrade it logged in automatically (SSO) when we did go to mesh.domainname.com

**Comment by wh1te909** [comment]
you have to do a take control on any agent so that the session will login in ure browser. then try it again
if still doesn't work then just login with mesh username and password (was printed out at end of install script)
if you didn't save it follow instructions here to reset password https://wh1te909.github.io/tacticalrmm/faq/#how-do-i-recover-my-meshcentral-login-credentials

**Comment by frankemann** [comment]
yeah, one login to any agent, then it worked.
Thanks!
