### ISSUE TITLE
REST API Access

### ISSUE THREAD

**Issue by unplugged216** [wh1te909/tacticalrmm#468]
**Is your feature request related to a problem? Please describe.**
Not really a problem more of a documentation/organizational request. Digging around in the source and also watch har dumps and so on, I have noticed there seems to a fully operable API within TRMM. This is kind of a "duh" statement being it is running a VueJS front end lol. However, this API would be tremendously useful for onboarding, management, and general orchestration. As I understand the API now, in regards to authentication, you must provide a username, password, and TFA token and then an "api key" or authorization taken is returned. It appears the backend is not using a standard version of a Bearer token for example the header value is "Authorization: Token kljhfdslkuhfwe......." instead of "Authorization: Bearer l;kjfklsdfjhsdlfkjhsdf...". This is not necessarily a problem per se. It will just require a developer to work a little harder at coding in the API authorization. Then we have the TFA token to deal with. Again, not a major issue, it will just require some extra work to generate the token each time. It does appear, JWT is the current method just with a modified header. 

**Describe the solution you'd like**
Allow for the generation of API tokens from the GUI with permissions and ip restrictions. 

**Describe alternatives you've considered**
Working with the aforementioned caveats.

**Comment by wh1te909** [comment]
good request yea as you said, the entire app is just one big api that returns json lol just needs documentation

for now a trick to just get an auth token that you can use indefinitely, is to do a "Manual" agent install and set a very long expiry and then just copy the `--auth <token>` from the command that it spits out and you can use that in whatever client you want to call any of trmm's endpoints (except for any endpoints that being with `/api/v3/` those are reserved for actual agents and those use a different auth system for security reasons, so that if an agent is compromised, it's auth token cannot be used to do anything except change data for that agent alone)

And yea we're using django's built in auth token module for this (actually using [django-rest-knox](https://github.com/James1345/django-rest-knox)) so that's why the headers are a bit different format than standard jwt

**Comment by zharding** [comment]
Right on thank you. 

I did manufacture another workaround that I can tie a "user" too and perform actions such as create clients, sites, etc. It effectively logs in as a user using username, password, and otp. It takes the returned token and uses only during the action. The issue I am facing there is the storage of the credentials and the potential harm since I do not see a permissions schema in TRMM yet. I am also interested in documenting these end-points btw. I have already started a postman collection and can make it available if appropriate.

**Comment by sadnub** [comment]
Stateless API access without 2fa will be available in the next release. An API Token will need to be created and it is tied to a user account. It will get it's permissions from the user account selected, so API access can be locked down to only what it needs. Then just need to include the X-API-KEY Header with the generated token.

```
curl https://[domain]/automation/policies/ -X GET -H "X-API-KEY: J57BXCFDA2WBCXH0XTELBR5KAI69CNCZ"
```

**Comment by wh1te909** [comment]
added in release 0.8.3
