### ISSUE TITLE
Timer for Remote control in audit log

### ISSUE THREAD

**Issue by garfield50** [wh1te909/tacticalrmm#495]
hi all,

Your work is amazing !!! continue like that !!!! just an idea, can you use a timer for the remote control in the audit log to know the duration of the remote control.

Because i can give a log with connection duration every months to my customer. to provide proof of connection

Sorry, my English is bad because I am French.

Thank you.

**Comment by wh1te909** [comment]
Hi, remote control is handled by [Mesh Central](https://github.com/Ylianst/MeshCentral) which is a separate product. Mesh keeps track of timers, there's no way for me to do this in tactical so you'll need to query the meshcentral mongo database or check their docs for how to keep track.

Only thing I can do in tactical is time when someone opens meshcentral but this is useless because that just opens an iframe. Clicking the actual "connect" button inside the iframe is what we need to time which I cannot do, and anyway that's logged in mongo.

**Comment by dinger1986** [comment]
Timers are recorded in mesh audit logs
