### ISSUE TITLE
Brand new install can't login

### ISSUE THREAD

**Issue by kb8zgl** [wh1te909/tacticalrmm#50]
Excited to try out your project.  I have a brand new install, it had some errors during the installation (which I copied down the entire process terminal output).  The login comes up, but my username and password fail to work (I put them in lastpass immediately on creating them), so I know I have them accurate.

A bit stuck on where things went wrong, thanks.

**Comment by wh1te909** [comment]
Hi! Ok can you please post the entire output (make sure to hide anything sensitive) so I can see the errors

**Comment by kb8zgl** [comment]
[TacticalRMMInstallOutput.zip](https://github.com/wh1te909/tacticalrmm/files/5087042/TacticalRMMInstallOutput.zip)

It looked good until near the end where it was creating the mesh central account.  This is just a text file zipped for upload, let me know if you need a different format.  Thanks for looking!

**Comment by wh1te909** [comment]
thanks! you're using an older version of the install script. I've recently updated it to fix that error please download from here and run again (you'll need to wipe the VPS first since install script will only work on fresh install of ubuntu)

https://raw.githubusercontent.com/wh1te909/tacticalrmm/develop/install.sh

**Comment by kb8zgl** [comment]
Thanks sorry about that, I had pulled the script last week.  I'll get it replaced and try again.  I had a snapshot, so minimal concern.  Thanks for letting me know.

**Comment by wh1te909** [comment]
No worries, let me know how it goes

**Comment by kb8zgl** [comment]
Install went much better, do I still want to run update.sh after?

**Comment by wh1te909** [comment]
sweet. no the update script only needs to be run whenever there is a new commit to the develop branch to get new features, so if you just installed, my last push was a few hours ago so you're good.

since I haven't released an "official" version yet the update script is pretty inefficient it just will update to the latest changes whether you need them or not, it will be alot smarter though soon once i work out a versioning system to determine what exactly needs to be updated.

**Comment by kb8zgl** [comment]
Have my first agent up and working, we will give it some testing, thanks!
