### ISSUE TITLE
Add possibility to CHOOSE certificate

### ISSUE THREAD

**Issue by Kptainflintt** [wh1te909/tacticalrmm#593]
I really love TacticalRMM features and concept but I can't setup it in my environnement.

I actually have 3 domains, each have already an existing certificate, but I can't use it.
I only want to use TacticalRMM locally, on my AD domain but again, can't use root CA

So I have to buy a domain (Freenom is not fonctionning) just to setup.

Why we cannot use it without it? (even witch a self-signed certificate)

**Comment by wh1te909** [comment]
because certain features don't work with a self signed certificate like [NATS](https://nats.io/) which is a core part of the software. You're welcome to test with using your own certificates and if you get it working feel free to create a PR. Also not sure why Freenom is not working for you, there are many people using freenom domains to run tacticalrmm.
