### ISSUE TITLE
MeshCentral Config Essentially Read-Only

### ISSUE THREAD

**Issue by Kuuchuu** [wh1te909/tacticalrmm#603]
Docker Install

Unable to modify MeshCentral config.json. Config resets to default values upon changing and container reload. This forces me to double proxy the entire setup as I currently use Swag to deploy all my other services. Not being able to modify the config.json also means I am unable to customize the server. If there is a way to change it I haven't found it, any guidance would be appreciated!

**Comment by wh1te909** [comment]
sounds like you would want to do a normal install instead of docker if you plan to customize things. with normal install you are free to change whatever configs you want, although they technically won't be supported anymore but won't be overwritten. otherwise i am not that familiar with docker so maybe @sadnub would know of a way in docker

**Comment by technoicon** [comment]
@sadnub and I spoke about exposing some of these values via an .env file.

maybe let us know exactly what you want to change and he can make it part of it.

I personally want the IP whitelist of mesh central exposed so we can edit this.

**Comment by sadnub** [comment]
In the next release there will be a MESH_PERSISTENT_CONFIG option that you can set to 1 in the docker .env file and it will keep the mesh configuration changes.

**Comment by wh1te909** [comment]
released in 0.8.0
