### ISSUE TITLE
Feature Request: Policies For Servers and/or Workstations

### ISSUE THREAD

**Issue by bradhawkins85** [wh1te909/tacticalrmm#63]
Would it be possible to configure a policy so that it only applies to Servers or Workstations (or both)?
E.G. Disk Space check for Servers vs Workstations could be at different percentages? Or only apply a Service Check to Servers etc.

Perhaps two tick boxes, Apply To: Servers, Workstations when creating/editing a policy?

**Comment by bradhawkins85** [comment]
sadnub that sounds good, would it be too much to allow multiple policies per container as well?
It will increase the flexibility of what can be done with policies in the long run.

**Comment by sadnub** [comment]
@bradhawkins85 I was having issues getting the multiple policies to work properly. I was also unsure which checks should take precedence if there were multiple conflicting checks applied to site.

I am thinking a group-based approach might be more flexible, but that would take a while to implement.

I did just submit a PR to separate the workstation/server policies. That should allow for more flexibility.

One thing to note is the policies applied to clients and sites will need to be added again since the DB schema changed.

**Comment by sadnub** [comment]
This PR has been merged. Let me know if you have any issues!
