### ISSUE TITLE
Mesh privacy bar / sharing desktop with faked value

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#687]
**Server Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Chrome
 - RMM Version (as shown in top left of web UI): 0.8.2

**Installation Method:**
  - [X ] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.1
- Agent OS: Windows

**Describe the bug**
When using Privacy Bar, the name of the "Sharing desktop with" is a dummy value like fsjhgdhigh

**To Reproduce**
using mesh agent, right clic Connect and Select  Privacy Bar

**Expected behavior**
Name of the agent should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/84961534/131896450-f3e70bea-b619-4750-8594-150b4382992e.png)

**Additional context**

**Comment by dinger1986** [comment]
I don't know about docker at all but is that the username you setup that's used for mesh?

Or possibly the real name setup?

**Comment by guillaumebottollier** [comment]
mmmmh you're right this is the mesh username..
![image](https://user-images.githubusercontent.com/84961534/131897191-52a797d4-9b28-4268-b8cc-a1cca102a4aa.png)

how can we change it ? try to change it mesh ask for a username/password :(
(it's not a docker install but debian 10)

**Comment by dinger1986** [comment]
I misread....saw D and assumed docker 😂.

Easiest and best thing is to not change it. But you can change the nickname in mesh.

1. Log into tactical
2. Right click and take control on any PC
3. Go to https://mesh.yourdomain.com
4. Click on TacticalRMM Group (or go to my account then Tactical RMM)
5. Click on Edit button next to User Consent and set the settings that you would like configured
6. In User Authorisations and select the default account created by Tactical (if you have mulitple it should show as Full Administrator)
7. Next to Real Name  click the edit button and change this to the name you want customers to see, for example for us we have it set as the business name rather than individuals

**Comment by guillaumebottollier** [comment]
you make my day...
THANK you !!!
