### ISSUE TITLE
overdue time by default for new agent

### ISSUE THREAD

**Issue by cmiscloni** [wh1te909/tacticalrmm#689]
Overdue time is always back to default when a new agent is added to the Dashboard,the possibility to apply a custom in settings by default will be great.
Thanks

**Comment by silversword411** [comment]
52 years is a nice indicator that a client hasn't done an update yet. What would you set it to otherwise?

**Comment by cmiscloni** [comment]
Actually, my agents comes overdue after a very short period. I change it by cli but it's not applied on new agents. Maybe let the administrator decide what the best time for him with a specific Global Setting.

**Comment by wh1te909** [comment]
the default is hardcoded in the django model and created when your database is created during initial install. can't override it after. this is why the management command exists. you can setup the management command in a cronjob if you want that way you don't have to manually run it from cli. I would just have it run every 5 minutes or so that way it will catch all new agents.
