### ISSUE TITLE
Download link for mesh agent HS

### ISSUE THREAD

**Issue by guillaumebottollier** [wh1te909/tacticalrmm#709]
**Server Info (please complete the following information):**
 - OS: [Debian 10]
 - Browser: [all]
 - RMM Version (as shown in top left of web UI): 0.8.3

**Installation Method:**
  - [X] Standard

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): 1.6.2
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2] : NA

**Describe the bug**
Dear All,
i haven't uploaded the 32bits mesh agent during tactical's install, though i never need it but now needed it is...
the link https://mesh.domain.com:443/agentinvite?c= i've backuped up seems not to work anymore, with message NOT FOUND.
What can i do to download the 32bits mesh agent and upload it to tactical ?
Thanks !

**Comment by dinger1986** [comment]
Take control of any machine via tactical, (you can also remote back ground for files or terminal). 
Then go to mesh.yourdomain.com and it should log you in automatically.
Click add agent, you can then download from there. 

The invite link created wont last for very long (for security) which is why it didnt work.
