### ISSUE TITLE
mesh logintoken not working in docker

### ISSUE THREAD

**Issue by wh1te909** [wh1te909/tacticalrmm#8]
The following does not work when running in docker since meshcentral is running in it's own container and the api doesn't have access to it, therefore remote desktop, terminal and file browser are not working.

https://github.com/wh1te909/tacticalrmm/blob/a79775c8afe1d5c1cf4062cbea96b93ba8b9ba4e/api/tacticalrmm/agents/views.py#L121-L128

**Comment by sadnub** [comment]
This is interesting. I checked through the MeshCentral docs and code and don't really see an API to add these from an external system. I might have missed something though. We might be able to make an addon package to be able to call an endpoint to create the token. The only other thing I could think was to add the fields directly into MongoDB. I think in another issue you suggested creating a separate MongoDB instance to be able to support more clients. So that might work to fix both of those issues.

**Comment by sadnub** [comment]
I actually found this:
https://github.com/Ylianst/MeshCentral/issues/59

Looks like you can get a login token remotely.

**Comment by wh1te909** [comment]
Awesome thanks for finding that! Used it to fix the issue.
