### ISSUE TITLE
Different service check dialogs in agent vs automation manager

### ISSUE THREAD

**Issue by silversword411** [wh1te909/tacticalrmm#858]
Automation manager has:

![2021-12-12_132810 - check service1](https://user-images.githubusercontent.com/13395348/145724804-9f53520a-a9b2-4337-9fc4-e626c6753252.png)

Agent check only has:

![2021-12-12_132810 - check service2](https://user-images.githubusercontent.com/13395348/145724819-b34894ce-309a-4470-99fe-ef8c40aa5610.png)

**Comment by dinger1986** [comment]
Is that not ok though? It will show all the services it detects on that one machine (that it has access to)

**Comment by silversword411** [comment]
I wouldn't expect the dialogs to be different capabilities, should be consistent. If there's a reason they can close issue :)

**Comment by dinger1986** [comment]
I think it's worse being able to type it in on an agent. But yes happy leaving it up to the devs

**Comment by wh1te909** [comment]
yes this is intentional, agent service checks don't need an option to choose or enter manually because we already know what services are available on that agent. When creating a policy check, we don't know what agents it will apply to, so we have no way of knowing what services are available. Which is why the user needs to enter manually or choose from a list of defaults which is just some array we hardcoded with popular services.
