### ISSUE TITLE
Software Chocolatey hardcoded versions

### ISSUE THREAD

**Issue by ArmandusNereus** [wh1te909/tacticalrmm#86]
Example: 

When installing Citrix Workspace Tacticalrmm shows old version and redirects to a newer version on Chocolatey.
The install command is Command line: "C:\ProgramData\Chocolatey\choco.exe" install citrix-workspace --version 19.11.0.50 --no-progress --yes 

Wat is the version number in TacticalRMM but not in Chocolatey. Is there a way to update the repository?

**Comment by wh1te909** [comment]
Hi so yea when you first install tacticalrmm it uses this file https://github.com/wh1te909/tacticalrmm/blob/develop/api/tacticalrmm/software/chocos.json
to seed the database with an initial list of software, I created that file a long time ago so that's why versions are old.

There is a background job that runs every night at 4am, it will basically pick one agent that's online at random and run a chocolately list command to get the latest software versions from chocolately's website, and then update the database, for example here is what mine looks like

![citrix](https://user-images.githubusercontent.com/7434746/91750225-9912c080-eb77-11ea-9c49-8f6b2008346b.PNG)

If you want to manually update the chocolatey database you can do this (this is what runs every night around 4am)

```
cd /rmm/api//tacticalrmm/
source ../env/bin/activate
python manage.py shell

from software.tasks import update_chocos
update_chocos.delay()
```

Then wait a bit and it should update software list.
