### ISSUE TITLE
How to deploy TRMM with Docker Swarm and behind Nginx

### ISSUE THREAD

**Issue by SysEngDan** [wh1te909/tacticalrmm#964]
I maintain and operate an existing Docker Swarm cluster. All traffic is reverse proxied by Nginx which also performs the SSL termination. Because of this **none of the downstream applications have access to any copy of the SSL certificate, they are only configured as being reverse proxied**.

During my attempt to deploy TRMM with Docker Swarm, which included re-writing the docker-compose.yml file, I'm still under the impression that Mesh Central needs a copy of the SSL cert. There's even a field in the Mesh Central settings called ` "TLSOffload": "${NGINX_HOST_IP}"`, but this IP of the Nginx containers (and there's one running on each host) isn't something that's static.

Did anyone else find out how to handle this?

**Comment by dinger1986** [comment]
You might have more luck on #unsupported on discord. Not something that's supported but someone might have some ideas.

**Comment by SysEngDan** [comment]
I'm a little surprised that it would be unsupported as there is a significant number of production services hosted all over the world in this manner. Providing copies of SSL certificates to downstream applications has already become a management nightmare. This is exactly why softwares like Nginx, Apache, HAProxy, Trafik, and many more, offer SSL termination so that each and every app doesn't need to be configured with certificates. 

Could we consider using this ticket to request this functionality be added?

**Comment by silversword411** [comment]
Welcome to Tactical RMM!

You should review: https://docs.tacticalrmm.com/unsupported_guidelines/

We have a specific process that is recommended and tested by devs to make sure TRMM works. For everyone. Always.

That said: https://docs.tacticalrmm.com/faq/#is-it-possible-to-use-xxx-proxy-server-with-tactical-rmm
We're not hear to provide infinite support to infinite varieties of system configurations and implementations. 

We support one way publicly without cost. Follow the official instructions, and it'll work.

We encourage, and appreciate any contributions you would like to improving the breadth of the documented options available. 

#Unsupported basically means you've strayed from the documented path of: Do 1 2 3 and it'll work. 

Join us on discord, and we can discuss there. Going to close this issue for now because issues are for specific TRMM features/bugs.
